# Gunakan image PHP resmi dengan versi yang sesuai
FROM php:8.0-fpm

# Set timezone jika diperlukan
ENV TZ=Asia/Jakarta

# Install dependencies sistem
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    supervisor \
    libzip-dev

# Install ekstensi PHP yang diperlukan
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Atur direktori kerja
WORKDIR /var/www

# Salin file aplikasi ke container
COPY . .

# Install dependensi aplikasi
RUN composer install --no-dev --optimize-autoloader

# Generate APP_KEY
RUN php artisan key:generate

# Ubah permission storage dan cache
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# Expose port 8000
EXPOSE 8000

# Jalankan migrasi dan seeder jika diperlukan
RUN php artisan migrate --force
RUN php artisan db:seed --force

# Jalankan supervisor untuk menjalankan php-fpm dan nginx
CMD php artisan serve --host=0.0.0.0 --port=8000
